//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Letter()
        {
            this.AttachmentFiles = new HashSet<AttachmentFile>();
            this.SentLetters = new HashSet<SentLetter>();
        }
    
        public int LetterID { get; set; }
        public string LetterSubject { get; set; }
        public string LetterCaption { get; set; }
        public string LetterNo { get; set; }
        public string LetterCreatedDate { get; set; }
        public int LetterUserID { get; set; }
        public byte LetterSecurityType { get; set; }
        public byte LetterForceType { get; set; }
        public byte LetterArchiveType { get; set; }
        public byte LetterFollowingType { get; set; }
        public byte LetterAttachmentType { get; set; }
        public byte LetterType { get; set; }
        public byte LetterDraftType { get; set; }
        public string LetterAbstract { get; set; }
        public byte LetterAnswerType { get; set; }
        public string LetterAnswerDeadLine { get; set; }
        public string LetterReffrence { get; set; }
        public Nullable<int> LetterReplyID { get; set; }
        public string LetterSentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentFile> AttachmentFiles { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentLetter> SentLetters { get; set; }
    }
}
