//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsSubject { get; set; }
        public string NewsContext { get; set; }
        public int NewsUserID { get; set; }
        public string NewsDate { get; set; }
        public byte[] NewsAttachment { get; set; }
        public string NewsAttachmentFileName { get; set; }
        public Nullable<int> NewsAttachmentFileSize { get; set; }
    
        public virtual User User { get; set; }
    }
}
