//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentLetter
    {
        public int SentLetterID { get; set; }
        public int SentSendedLetterID { get; set; }
        public int SentUserID { get; set; }
        public Nullable<byte> SentReadType { get; set; }
    
        public virtual Letter Letter { get; set; }
        public virtual User User { get; set; }
    }
}
