//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int SupID { get; set; }
        public string SupSubject { get; set; }
        public string SupCaption { get; set; }
        public int SupUserID { get; set; }
        public string SupDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
