//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPart
    {
        public int SPartID { get; set; }
        public string SPartName { get; set; }
        public string SPartDetail { get; set; }
        public Nullable<int> SPartLevel { get; set; }
    }
}
