//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Jobs
    {
        public int JobsID { get; set; }
        public string JobsName { get; set; }
        public string JobsDetails { get; set; }
        public Nullable<int> JobsLevel { get; set; }
        public Nullable<int> JobsDetermineLevel { get; set; }
        public Nullable<int> JobsChild { get; set; }
    }
}
