//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Users
    {
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserPersonalID { get; set; }
        public string UserEmail { get; set; }
        public byte UserActivity { get; set; }
        public byte UserGender { get; set; }
        public string View_UserGender { get; set; }
        public string View_UserActivity { get; set; }
        public string UserTel { get; set; }
        public string UserBrithDate { get; set; }
        public byte[] UserImage { get; set; }
        public byte[] UserSignature { get; set; }
        public string UserRegisteredDate { get; set; }
    }
}
