//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Works
    {
        public int WorkID { get; set; }
        public string WorkSubject { get; set; }
        public string WorkCaption { get; set; }
        public int WorkUserID { get; set; }
        public int WorkJobID { get; set; }
        public string WorkDoneDate { get; set; }
        public Nullable<int> WorkDoneTime { get; set; }
        public string JobsName { get; set; }
        public string FullName { get; set; }
    }
}
